version: '3.3'

services:
  reverse-proxy:
    image: traefik # The official Traefik docker image
    command: --api --docker # Enables the web UI and tells Tr√¶fik to listen to docker
    ports:
      - "9001:80"     # The HTTP port
      - "8080:8080" # The Web UI (enabled by --api)
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events
      - ./traefik.toml:/traefik.toml
      - ./server.crt:/server.crt
      - ./server.key:/server.key
  whoami:
    image: jeromechrist/whoami:latest # A container that exposes an API to show its IP address
    # build: .
    environment: 
      - ASPNETCORE_URLS=http://+:80
      - PATH_BASE=/whoami/
    labels:
      - "traefik.backend=whoami"
      - "traefik.frontend.rule=Path: /whoami/"
      - "traefik.backend.port=9001"
      - "traefik.default.protocol=http"